#!/usr/bin/env python3
"""Generate demand data for a scenario and write it as a standalone ``demand.py``.

Usage::

    python _generate_demand.py scenario.hangzhou0 --days 20 --per-day 50 --step 10.0

This writes ``DEMAND_ORDERS`` to the scenario's ``demand.py`` file.
If the file already exists it is skipped — delete it first to regenerate.
"""

import argparse
import os
import sys


def generate(
    scenario_name: str,
    days: int = 20,
    per_day: int = 50,
    start_time_step: float = 10.0,
) -> str:
    """Return Python source for ``DEMAND_ORDERS`` (daily FG → sink consumption)."""

    import importlib
    config = importlib.import_module(f"{scenario_name}.config")
    N = config.N

    lines: list[str] = []
    _w = lines.append

    _w('"""Demand orders for %s.' % scenario_name)
    _w('Auto-generated by _generate_demand.py.  Edit manually, or re-run.')
    _w('"""')
    _w("DEMAND_ORDERS: list[dict] = []")
    _w("")

    _w("# =======================================================================")
    _w("# DEMAND ORDERS  —  daily FG consumption (fg_storage -> sink)")
    _w("# =======================================================================")
    _w("# Generated by _generate_demand.py")
    _w("#")
    _w("# Each day, %.0f time units, consume %d units of each FG SKU."
       % (start_time_step, per_day))
    _w("")

    for day in range(days):
        t = day * start_time_step
        for i in range(1, N + 1):
            _w("DEMAND_ORDERS.append(dict(")
            _w("    sku='SKU_%d'," % i)
            _w("    quantity=%d," % per_day)
            _w("    from_node='fg_storage',")
            _w("    to_node='sink',")
            _w("    start_time=%.1f," % (t + 0.5))
            _w("))")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("scenario", help="Scenario directory name")
    parser.add_argument("--days", type=int, default=20, help="Number of demand days")
    parser.add_argument("--per-day", type=int, default=50,
                        help="Units consumed per FG SKU per day")
    parser.add_argument("--step", type=float, default=10.0,
                        help="Time units per day (default 10.0)")
    args = parser.parse_args()

    source = generate(args.scenario, days=args.days, per_day=args.per_day,
                      start_time_step=args.step)
    out_path = os.path.join(*(args.scenario.split(".") + ["demand.py"]))
    if os.path.exists(out_path):
        print(f"  [SKIP] {out_path} already exists — delete it first to regenerate")
        return
    with open(out_path, "w") as f:
        f.write(source)
        f.write("\n")
    print(f"  [OK]  wrote DEMAND_ORDERS to {out_path}")


if __name__ == "__main__":
    main()
