#!/usr/bin/env python3
"""Generate ``safe_stock.py`` for a scenario from its ``init_stock.py``.

Usage::

    python _generate_safe_stock.py scenario.ss_hangzhou0b

Reads the scenario's config (topology, SKUs) and its generated
``init_stock.py``, then derives safe-stock levels, replenish quantities, and
action fields for every (SKU, storage) pair.

Output is written to ``{scenario_dir}/safe_stock.py``.
"""

import argparse
import importlib
import os

from typing import Any


def _classify_source_type(sku: str, nodes: dict[str, dict]) -> str:
    """'fg' for SKU_* items, 'wip' for production outputs, else 'raw_material'."""
    if sku.startswith("SKU_"):
        return "fg"
    for node_data in nodes.values():
        if node_data.get("type") == "production":
            if sku in node_data.get("bom", {}):
                return "wip"
    return "raw_material"


def _find_produce_at(sku: str, nodes: dict[str, dict]) -> str | None:
    """First production node whose BOM has *sku* as an output key."""
    for name, nd in nodes.items():
        if nd.get("type") == "production" and sku in nd.get("bom", {}):
            return name
    return None


def _find_edge_from(edges: list[dict], to_node: str) -> str | None:
    """``from_node`` of first edge to *to_node*; prefers ``'source'``."""
    candidates = [e["from_node"] for e in edges if e["to_node"] == to_node]
    if not candidates:
        return None
    return "source" if "source" in candidates else candidates[0]


def _find_edge_to(edges: list[dict], from_node: str) -> str | None:
    for e in edges:
        if e["from_node"] == from_node:
            return e["to_node"]
    return None


def _ensure_min_qty(replenish_qty: int, init_qty: int) -> int:
    return 1 if replenish_qty == 0 and init_qty > 0 else replenish_qty


def generate(scenario_name: str) -> str:
    config = importlib.import_module(f"{scenario_name}.config")
    init_stock_mod = importlib.import_module(f"{scenario_name}.init_stock")

    nodes: dict[str, dict] = config.NODES
    edges: list[dict] = config.EDGES
    init_stock: dict[str, dict[str, int]] = init_stock_mod.INIT_STOCK

    lines: list[str] = []
    _w = lines.append

    _w(f'"""Safe-stock configuration for {scenario_name}.')
    _w("")
    _w("Auto-generated by _generate_safe_stock.py.")
    _w("Edit manually, or re-run the script to regenerate.")
    _w('"""')
    _w("")
    _w("")
    _w("SAFE_STOCK: list[dict] = [")

    total = sum(len(skus) for skus in init_stock.values())
    done = 0

    for node_name in sorted(init_stock, key=_node_sort_key):
        skus = init_stock[node_name]
        is_output = node_name.startswith("output_")
        is_lineside = node_name.startswith("lineside_")
        is_wip_fg = node_name in ("WIP_storage", "fg_storage")

        if is_output:
            resolved_action_val = _find_edge_to(edges, node_name) or "unknown"
        elif is_lineside or not is_wip_fg:
            resolved_action_val = _find_edge_from(edges, node_name) or "unknown"

        for sku in sorted(skus, key=_sku_sort_key):
            init_qty = skus[sku]
            done += 1
            print(f"  [{done}/{total}] {node_name} / {sku}  (qty={init_qty})")

            if is_output and init_qty == 0:
                safe_stock = 1
                replenish_qty = 400
            else:
                safe_stock = init_qty * 80 // 100
                replenish_qty = _ensure_min_qty(init_qty * 50 // 100, init_qty)

            source_type = _classify_source_type(sku, nodes)

            if is_output:
                action_key = "push_to"
                action_val = resolved_action_val
            elif is_lineside:
                action_key = "replenish_from"
                action_val = resolved_action_val
            elif is_wip_fg:
                action_key = "produce_at"
                action_val = _find_produce_at(sku, nodes) or "unknown"
            else:
                action_key = "replenish_from"
                action_val = resolved_action_val

            _w(f'    dict(sku={sku!r}, safe_stock={safe_stock},')
            _w(f'         replenish_qty={replenish_qty},')
            _w(f'         storage={node_name!r}, {action_key}={action_val!r},')
            _w(f'         source_type={source_type!r}),')

    _w("]")
    _w("")

    return "\n".join(lines)


def _node_sort_key(name: str) -> tuple:
    prio = {
        "raw_material_storage": 0,
        "main_storage": 1,
        "WIP_storage": 2,
        "fg_storage": 3,
        "lineside": 4,
        "output": 5,
    }
    for prefix, p in prio.items():
        if name.startswith(prefix):
            return (p, name)
    return (9, name)


def _sku_sort_key(sku: str) -> tuple:
    if sku.startswith("SKU_"):
        return (2, sku)
    if sku.startswith(("sauce_", "powder_", "veg_")):
        return (1, sku)
    return (0, sku)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate safe_stock.py from init_stock.py for a scenario."
    )
    parser.add_argument(
        "scenario",
        help="Dotted scenario name, e.g. scenario.ss_hangzhou0b",
    )
    args = parser.parse_args()

    source = generate(args.scenario)
    out_path = os.path.join(*(args.scenario.split(".") + ["safe_stock.py"]))

    if os.path.exists(out_path):
        print(f"\n  [SKIP] {out_path} already exists — delete it first to regenerate")
        return

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(source)
    print(f"\n  [OK]  wrote {out_path}")


if __name__ == "__main__":
    main()
