#!/usr/bin/env python3
"""Generate ``safe_stock.py`` for a scenario by reading its config.

Usage::

    python generate_stock.py scenario_hangzhou0

Output is written to ``{scenario}/safe_stock.py``.
"""

import importlib
import os
import sys


def generate(scenario_name: str) -> str:
    """Return the Python source for a ``safe_stock.py`` file.

    The source is generated by reading the scenario's ``config`` module
    and building ``SAFE_STOCK`` entries for every known SKU.
    """

    config = importlib.import_module(f"{scenario_name}.config")

    N = config.N
    lines: list[str] = []
    _w = lines.append

    _w('"""Safe-stock configuration for the %s scenario.' % scenario_name)
    _w('')
    _w('Auto-generated by generate_stock.py.  Edit manually, or re-run')
    _w('the script to regenerate.')
    _w('"""')
    _w('')
    _w('')
    _w('SAFE_STOCK: dict[str, dict] = {}')
    _w('')

    # ---- helpers ---------------------------------------------------------
    RAW_SOURCE = "source"
    RAW_SAFE = 2000
    RAW_REPLENISH = 1000
    WIP_SAFE = 800
    WIP_REPLENISH = 400
    FG_SAFE = 200
    FG_REPLENISH = 100

    def add_raw(sku: str, storage: str):
        _w("SAFE_STOCK[%r] = dict(" % sku)
        _w("    safe_stock=%d, replenish_qty=%d," % (RAW_SAFE, RAW_REPLENISH))
        _w("    storage=%r, source_type='raw_material'," % storage)
        _w("    replenish_from=%r," % RAW_SOURCE)
        _w(")")
        _w("")

    # -- raw materials in raw_material_storage -----------------------------
    _w("# raw materials — raw_material_storage")
    _w("")
    for i in range(1, N + 1):
        add_raw(f"smallpack_s_{i}", "raw_material_storage")
        add_raw(f"smallpack_p_{i}", "raw_material_storage")
    for i in range(1, 5):
        add_raw(f"meat_{i}", "raw_material_storage")
        add_raw(f"oil_{i}", "raw_material_storage")
        add_raw(f"vegetable_{i}", "raw_material_storage")
        add_raw(f"original_powder_{i}", "raw_material_storage")

    # -- raw materials in main_storage_1 (veg ingredients) -----------------
    _w("# raw materials — main_storage_1 (veg ingredients)")
    _w("")
    for i in range(1, N + 1):
        add_raw(f"smallpack_v_{i}", "main_storage_1")
    for i in range(1, 5):
        add_raw(f"dry_veg_{i}", "main_storage_1")

    # -- packaging ---------------------------------------------------------
    _w("# packaging")
    _w("")
    for sku in ("bow", "cap", "pack"):
        add_raw(sku, "main_storage_1")

    # -- WIP: sauces -------------------------------------------------------
    _w("# WIP — sauces")
    _w("")
    for i in range(1, N + 1):
        _w("SAFE_STOCK[%r] = dict(" % f"sauce_{i}")
        _w("    safe_stock=%d, replenish_qty=%d," % (WIP_SAFE, WIP_REPLENISH))
        _w("    storage='WIP_storage', source_type='wip',")
        _w("    produce_at=%r," % f"workstation_sauce_{i}")
        _w(")")
        _w("")

    # -- WIP: powders ------------------------------------------------------
    _w("# WIP — powders")
    _w("")
    _powder_line_sku = {1: [1, 7], 2: [2, 8], 3: [3, 9], 4: [4, 10], 5: [5], 6: [6]}
    _powder_sku_to_line = {}
    for pl, skus in _powder_line_sku.items():
        for pi in skus:
            _powder_sku_to_line[pi] = pl
    for i in range(1, N + 1):
        pl = _powder_sku_to_line[i]
        _w("SAFE_STOCK[%r] = dict(" % f"powder_{i}")
        _w("    safe_stock=%d, replenish_qty=%d," % (WIP_SAFE, WIP_REPLENISH))
        _w("    storage='WIP_storage', source_type='wip',")
        _w("    produce_at=%r," % f"workstation_powder_{pl}")
        _w(")")
        _w("")

    # -- WIP: veg ----------------------------------------------------------
    _w("# WIP — veg")
    _w("")
    for i in range(1, N + 1):
        _w("SAFE_STOCK[%r] = dict(" % f"veg_{i}")
        _w("    safe_stock=%d, replenish_qty=%d," % (WIP_SAFE, WIP_REPLENISH))
        _w("    storage='main_storage_1', source_type='wip',")
        _w("    produce_at='workstation_veg',")
        _w(")")
        _w("")

    # -- FG ----------------------------------------------------------------
    _w("# FG")
    _w("")
    line_sku_map = {
        1: [1, 6], 2: [2, 7], 3: [3, 8], 4: [4, 9], 5: [5, 10],
        6: [1], 7: [2], 8: [3],
        9: [4], 10: [5], 11: [6], 12: [7], 13: [8], 14: [9], 15: [10],
        16: [1, 6],
    }
    sku_to_line = {}
    for ln, skus in line_sku_map.items():
        for si in skus:
            if si not in sku_to_line:
                sku_to_line[si] = ln
    for i in range(1, N + 1):
        ln = sku_to_line[i]
        _w("SAFE_STOCK[%r] = dict(" % f"SKU_{i}")
        _w("    safe_stock=%d, replenish_qty=%d," % (FG_SAFE, FG_REPLENISH))
        _w("    storage='fg_storage', source_type='fg',")
        _w("    produce_at=%r," % f"workstation_noodle_{ln}")
        _w(")")
        _w("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    scenario = sys.argv[1]
    source = generate(scenario)
    out_path = os.path.join(scenario, "safe_stock.py")
    if os.path.exists(out_path):
        print(f"  [SKIP] {out_path} already exists — delete it first to regenerate")
        return
    with open(out_path, "w") as f:
        f.write(source)
    print(f"  [OK]  wrote {out_path}")


if __name__ == "__main__":
    main()
