"""Demand orders for scenario.t_hangzhou1.
Auto-generated by _generate_demand.py.  Edit manually, or re-run.
"""
DEMAND_ORDERS: list[dict] = []

# =======================================================================
# DEMAND ORDERS  —  daily FG consumption (fg_storage -> sink)
# =======================================================================


DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=5000,
    from_node='fg_storage',
    to_node='sink',
    start_time=10000,
))
