"""Demand orders for scenario.t_hangzhou1.
Auto-generated by _generate_demand.py.  Edit manually, or re-run.
"""
DEMAND_ORDERS: list[dict] = []

# =======================================================================
# DEMAND ORDERS  —  daily FG consumption (fg_storage -> sink)
# =======================================================================
# Generated by _generate_demand.py
#
# Each day, 10 time units, consume 50 units of each FG SKU.

DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=0.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_2',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=0.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_3',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=0.5,
))  


DEMAND_ORDERS.append(dict(
    sku='SKU_8',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=4000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_9',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=4000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_10',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=4000.5,
))




DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=14000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_5',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=14000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_10',
    quantity=22000,
    from_node='fg_storage',
    to_node='sink',
    start_time=14000.5,
))




DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=15000.5,
))


DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=25000.5,
))


DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=35000.5,
))

DEMAND_ORDERS.append(dict(
    sku='SKU_2',
    quantity=42000,
    from_node='fg_storage',
    to_node='sink',
    start_time=36000.5,
))

DEMAND_ORDERS.append(dict(
    sku='SKU_3',
    quantity=32000,
    from_node='fg_storage',
    to_node='sink',
    start_time=37000.5,
))

DEMAND_ORDERS.append(dict(
    sku='SKU_4',
    quantity=22000,
    from_node='fg_storage',
    to_node='sink',
    start_time=38000.5,
))
