"""Demand orders for scenario.w_hangzhou1.

Loads from data/demand.xlsx via :mod:`src._xlsx_loaders`.

Falls back to auto-generated hardcoded data when the xlsx file is absent.
"""

from pathlib import Path

DEMAND_ORDERS: list[dict] = []

_root = Path(__file__).resolve().parents[2] / "data"
_demand_path = _root / "demand.xlsx"

if _demand_path.exists():
    from src._xlsx_loaders import load_demand
    DEMAND_ORDERS = load_demand(_root)
else:
    DEMAND_ORDERS: list[dict] = []  # type: ignore[no-redef]
# Generated by _generate_demand.py
#
# Each day, 10 time units, consume 50 units of each FG SKU.

DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=0.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_2',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=0.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_3',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=0.5,
))  


DEMAND_ORDERS.append(dict(
    sku='SKU_8',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=4000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_9',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=4000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_10',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=4000.5,
))




DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=14000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_5',
    quantity=12000,
    from_node='fg_storage',
    to_node='sink',
    start_time=14000.5,
))
DEMAND_ORDERS.append(dict(
    sku='SKU_10',
    quantity=22000,
    from_node='fg_storage',
    to_node='sink',
    start_time=14000.5,
))




DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=1200,
    from_node='fg_storage',
    to_node='sink',
    start_time=15000.5,
))


DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=1200,
    from_node='fg_storage',
    to_node='sink',
    start_time=25000.5,
))


DEMAND_ORDERS.append(dict(
    sku='SKU_1',
    quantity=1200,
    from_node='fg_storage',
    to_node='sink',
    start_time=35000.5,
))

DEMAND_ORDERS.append(dict(
    sku='SKU_2',
    quantity=4200,
    from_node='fg_storage',
    to_node='sink',
    start_time=36000.5,
))

DEMAND_ORDERS.append(dict(
    sku='SKU_3',
    quantity=3200,
    from_node='fg_storage',
    to_node='sink',
    start_time=37000.5,
))

DEMAND_ORDERS.append(dict(
    sku='SKU_4',
    quantity=2200,
    from_node='fg_storage',
    to_node='sink',
    start_time=38000.5,
))
